[package]
name = "consume-arrow"
version.workspace = true
edition.workspace = true
documentation.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fastformat-rs = { workspace = true }
eyre = { workspace = true }
