[package]
name = "fastformat"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Fast world data converter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fastformat"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.21.1"
